services:
  headscale:
    image: image: docker.io/headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped

    command: serve

    volumes:
      - ./config/config.yaml:/etc/headscale/config.yaml:ro
      - ./data:/var/lib/headscale

    networks:
      - headscale

  caddy:
    image: docker.io/library/caddy:latest
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - headscale

networks:
  headscale:

volumes:
  caddy_data:
  caddy_config: