server_url: https://headscale.deinedomain.de

listen_addr: 0.0.0.0:8080

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

derp:
  server:
    enabled: false

log:
  format: text
  level: info